modLoader="javafml"
loaderVersion="[47,)"
license="ARR"
issueTrackerURL="https://github.com/tapeQ/Shine/issues"

[[mods]]
modId="shine"
version="${version}"
displayName="Shine"
description='''
Adds bloom, colored lighting, and stylized effects to Minecraft, without shaders.
'''
authors="tapeQ"
logoFile="assets/shine/shine4.png"

[[mixins]]
config="shine.mixins.json"

[[dependencies.shine]]
modId="forge"
mandatory=true
versionRange="[47.4,)"
ordering="NONE"
side="CLIENT"

[[dependencies.shine]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"

[[dependencies.shine]]
modId="embeddium"
mandatory=false
versionRange="[0.3,)"
ordering="NONE"
side="CLIENT"

[[dependencies.shine]]
modId="oculus"
mandatory=false
versionRange="[1.6,)"
ordering="NONE"
side="CLIENT"
